// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Project Cafecito",
            "url": "http://cafecito.tech",
            "email": "soumitsrah@cafecito.tech"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "get": {
                "description": "Returns event-kind sips sorted by ` + "`" + `created` + "`" + ` descending (newest first).\nWith ` + "`" + `response_type=text` + "`" + `, each event is rendered as a flat plain-text digest (field-per-line) instead of a JSON object — same data, fewer tokens for MCPs and AI agents.",
                "produces": [
                    "application/json",
                    "text/plain"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Search events",
                "operationId": "searchEvents",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "fetch specific event sips by UUID (RFC 4122), e.g. 339366bc-464d-582f-8132-6875ccc814d2",
                        "name": "ids",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "scalar tag filters (inclusive AND across supplied tags)",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "maxLength": 1024,
                        "type": "string",
                        "description": "semantic search query (max 1024 characters; requires embedder)",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "maximum": 1,
                        "minimum": 0,
                        "type": "number",
                        "default": 0.75,
                        "description": "minimum embedding similarity for ` + "`" + `q` + "`" + ` (0.0-1.0, higher = stricter)",
                        "name": "acc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date",
                        "description": "include events created on or after this date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "json",
                            "text"
                        ],
                        "type": "string",
                        "default": "json",
                        "description": "output format: json (default) returns a JSON array of flattened digests; text returns the same data as flat plain text without JSON syntax (lower token cost for MCPs and AI agents)",
                        "name": "response_type",
                        "in": "query"
                    },
                    {
                        "maximum": 128,
                        "minimum": 1,
                        "type": "integer",
                        "default": 16,
                        "description": "page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "plain-text event digests (one record per block) when response_type=text",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "204": {
                        "description": "no matching events"
                    },
                    "400": {
                        "description": "invalid query parameters or malformed UUID in ids",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "database or embedder error",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/related/{relationship}": {
            "get": {
                "description": "Returns sips linked to the supplied UUIDs through the requested relationship.\nWith ` + "`" + `response_type=text` + "`" + `, each related sip is rendered as a flat plain-text digest (field-per-line) instead of a JSON object — same data, fewer tokens for MCPs and AI agents.",
                "produces": [
                    "application/json",
                    "text/plain"
                ],
                "tags": [
                    "Related"
                ],
                "summary": "Get related sips by relationship",
                "operationId": "getRelatedSips",
                "parameters": [
                    {
                        "enum": [
                            "same_as",
                            "derived_from"
                        ],
                        "type": "string",
                        "description": "relationship to traverse",
                        "name": "relationship",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "source sip UUIDs (RFC 4122), e.g. b07049b5-54c0-50b0-a620-d3aea3f8a173",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "json",
                            "text"
                        ],
                        "type": "string",
                        "default": "json",
                        "description": "output format: json (default) returns a JSON array of flattened digests; text returns the same data as flat plain text without JSON syntax (lower token cost for MCPs and AI agents)",
                        "name": "response_type",
                        "in": "query"
                    },
                    {
                        "maximum": 128,
                        "minimum": 1,
                        "type": "integer",
                        "default": 16,
                        "description": "page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "plain-text related-sip digests (one record per block) when response_type=text",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "204": {
                        "description": "no related sips found"
                    },
                    "400": {
                        "description": "missing ids, invalid relationship, or malformed UUID",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "database error",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/signals": {
            "get": {
                "description": "Returns signal-kind sips sorted by ` + "`" + `created` + "`" + ` descending (newest first).\nWith ` + "`" + `response_type=text` + "`" + `, each signal is rendered as a flat plain-text digest (field-per-line) instead of a JSON object — same data, fewer tokens for MCPs and AI agents.",
                "produces": [
                    "application/json",
                    "text/plain"
                ],
                "tags": [
                    "Signals"
                ],
                "summary": "Search signals",
                "operationId": "searchSignals",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "fetch specific signal sips by UUID (RFC 4122), e.g. e7d7571a-13f0-56f0-8563-50863b79c781",
                        "name": "ids",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "scalar tag filters (inclusive AND across supplied tags)",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "maxLength": 1024,
                        "type": "string",
                        "description": "semantic search query (max 1024 characters; requires embedder)",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "maximum": 1,
                        "minimum": 0,
                        "type": "number",
                        "default": 0.75,
                        "description": "minimum embedding similarity for ` + "`" + `q` + "`" + ` (0.0-1.0, higher = stricter)",
                        "name": "acc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date",
                        "description": "include signals created on or after this date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "json",
                            "text"
                        ],
                        "type": "string",
                        "default": "json",
                        "description": "output format: json (default) returns a JSON array of flattened digests; text returns the same data as flat plain text without JSON syntax (lower token cost for MCPs and AI agents)",
                        "name": "response_type",
                        "in": "query"
                    },
                    {
                        "maximum": 128,
                        "minimum": 1,
                        "type": "integer",
                        "default": 16,
                        "description": "page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "plain-text signal digests (one record per block) when response_type=text",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "204": {
                        "description": "no matching signals"
                    },
                    "400": {
                        "description": "invalid query parameters or malformed UUID in ids",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "database or embedder error",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "Returns a paginated, alphabetically sorted list of unique tag strings extracted from event and signal sips. Tags can be passed to ` + "`" + `/events` + "`" + ` and ` + "`" + `/signals` + "`" + ` for scalar filtering.\nWith ` + "`" + `response_type=text` + "`" + `, tags are returned as a single comma-separated plain-text string instead of a JSON array.",
                "produces": [
                    "application/json",
                    "text/plain"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "List tags for filtering events and signals",
                "operationId": "listTags",
                "parameters": [
                    {
                        "enum": [
                            "json",
                            "text"
                        ],
                        "type": "string",
                        "default": "json",
                        "description": "output format: json (default) returns a JSON string array; text returns the same tags as comma-separated plain text (lower token cost for MCPs and AI agents)",
                        "name": "response_type",
                        "in": "query"
                    },
                    {
                        "maximum": 128,
                        "minimum": 1,
                        "type": "integer",
                        "default": 16,
                        "description": "page limit (items per page)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "pagination offset (number of items to skip)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "comma-separated tags when response_type=text",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "204": {
                        "description": "no matching tags"
                    },
                    "400": {
                        "description": "invalid pagination parameters",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "database error",
                        "schema": {
                            "$ref": "#/definitions/router.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "router.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid id: not-a-uuid"
                }
            }
        },
        "router.Event": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2026-06-28 Firefighters died and injuries occurred at Wyoming-Utah border.",
                        "2026-06-28 Large wildfire destroyed parts of ski resorts."
                    ]
                },
                "briefing": {
                    "type": "string",
                    "example": "On June 28, 2026, three U.S. firefighters died while battling rapidly spreading wildfires near the Colorado-Utah border; approximately 100 sq km burned. Temperatures reached 34°C with strong winds, prompting mass evacuations. The Snyder Fire merged with others, causing significant damage to infrastructure like ski resorts. Causes include severe drought and human factors. This incident reflects escalating regional wildfire risks driven by climate change."
                },
                "companies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "us_federal",
                        "us_state"
                    ]
                },
                "cross_domain_impacts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "public_safety: Increased risk of civilian casualties.",
                        "tourism: Disruption of winter sports facilities.",
                        "environmental: Habitat loss in mountainous areas."
                    ]
                },
                "event_type": {
                    "type": "string",
                    "example": "wildfire_outbreak"
                },
                "future_outlook": {
                    "type": "string",
                    "example": "Continued extreme fire seasons expected without mitigation efforts."
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "091726f8-421a-566d-9db8-339625f2ed9e"
                },
                "impact_level": {
                    "type": "string",
                    "enum": [
                        "low",
                        "medium",
                        "high"
                    ],
                    "example": "high"
                },
                "macro_context": {
                    "type": "string",
                    "example": "western_us_climate_crisis"
                },
                "people": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "firefighter_john_doe",
                        "governor_polis"
                    ]
                },
                "products": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "petróleo"
                    ]
                },
                "regions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "colorado",
                        "utah"
                    ]
                },
                "reported": {
                    "type": "string",
                    "example": "2026-06-28T22:49:07Z"
                },
                "site_name": {
                    "type": "string",
                    "example": "Example News"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "wildfire",
                        "climate_change",
                        "us",
                        "emergency_response"
                    ]
                }
            }
        },
        "router.Signal": {
            "type": "object",
            "properties": {
                "briefing": {
                    "type": "string",
                    "example": "On 2026-06-02, U.S. lawmakers and the Trump administration debated AI sovereign-wealth and compute-tax proposals amid soaring inflation..."
                },
                "drivers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "High inflation and rising consumer costs driven by supply-chain bottlenecks and geopolitical tensions."
                    ]
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2026-06-01: Senator Bernie Sanders introduced a 50% ownership tax on major AI firms"
                    ]
                },
                "forecast": {
                    "type": "string",
                    "example": "Short-term: Market volatility will persist, AI regulatory scrutiny will intensify, and consumer confidence remains low."
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "e7d7571a-13f0-56f0-8563-50863b79c781"
                },
                "impact_level": {
                    "type": "string",
                    "enum": [
                        "low",
                        "medium",
                        "high"
                    ],
                    "example": "high"
                },
                "impacted_domains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "finance",
                        "technology",
                        "cybersecurity",
                        "labor",
                        "healthcare",
                        "energy",
                        "policy"
                    ]
                },
                "impacts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "9.3% market sell-off across tech and financial sectors.",
                        "Decline in consumer confidence and increased credit-card delinquency."
                    ]
                },
                "reported": {
                    "type": "string",
                    "example": "2026-06-02T14:02:00-04:00"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "ai_sovereign_wealth_fund",
                        "ai_taxation",
                        "compute_tax",
                        "inflation",
                        "market_volatility"
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "Espresso API & MCP",
	Description:      "Espresso is a curated business intelligence product suite. Espresso API & MCP provides access to the underlying data store.\nA **sip** is the basic unit of information: action (micro data such as market performance for a day), event (a self-contained set of micro actions and actions), and signal (larger derived intelligence from related events and actions).\nAll sip identifiers are UUIDs (RFC 4122), for example `339366bc-464d-582f-8132-6875ccc814d2`. Pass them as strings in query parameters and path segments.\nList endpoints accept an optional `response_type` query parameter: `json` (default) or `text`. Both return the same underlying data; `text` renders it as flat plain text without JSON syntax, which reduces token cost for MCPs and AI agents.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
