name: Trigger auto deployment for cafecito-espresso-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cafecito-espresso-api-AutoDeployTrigger-77af90e6-b636-49f9-96ad-0d339e244a75.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAFECITOESPRESSOAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAFECITOESPRESSOAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAFECITOESPRESSOAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.CAFECITOESPRESSOAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAFECITOESPRESSOAPI_REGISTRY_PASSWORD }}
          containerAppName: cafecito-espresso-api
          resourceGroup: coffeemaker-rg
          imageToBuild: soumitsr/cafecito-espresso-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


